config/routes.rb
Rails.application.routes.draw do

  get 'contacts/new'
  get 'contacts/create'
  devise_for :users

  namespace :admin do
    get '', to: 'dashboard#index', as: '/'
    resources :issues
    resources :medias

    get 'users', to: 'registrations#index', as: 'users'
    get 'users/new', to: 'registrations#new', as: 'new_user'
    post 'users', to: 'registrations#create', as: 'create_user'
    get 'users/:id/edit', to: 'registrations#edit', as: 'edit_user'
    put 'users/:id/update', to:'registrations#update', as: 'update_user'
    delete 'users/:id', to: 'registrations#destroy', as:  'delete_user'

    get 'inbox', to: 'contacts#index', as: 'inbox'
    get 'toggle', to: 'contacts#toggle_read', as: 'toggle_read'
    get 'toggle_archived', to: 'contacts#toggle_archived', as: 'toggle_archived'

  end

  root to: 'issues#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :issues, only: [:index, :show] do
    resources :medias, only: [:index, :show]
  end

  resources :contacts, only: [:new, :create]
  get 'about', to: 'pages#about', as: 'about'
  get 'contact', to: 'pages#contact', as: 'contact'
  get 'news', to: 'pages#news', as: 'news'
end

app/models/issue.rb
class Issue < ApplicationRecord
  has_many :medias

  mount_uploader :cover_image, IssueCoverImageUploader

end

app/controllers/admin/issues_controller.rb
class Admin::IssuesController < ApplicationController
  before_action :authenticate_user!
  before_action :get_issue, only: %i[edit update]
  before_action :get_unread_contacts

  def index
    @issues = policy_scope(Issue).order(created_at: :desc)
  end

  def new
    @issue = Issue.new
    authorize @issue
  end

  def create
    @issue = Issue.new(issue_params)
    @issue.save
    authorize @issue
  end

  def edit
  end

  def update
    if @issue.update(issue_params)
      redirect_to admin_path
    else
      render 'admin/issues/edit'
    end
  end

  private

  def get_issue
    @issue = Issue.find(params[:id])
    authorize @issue
  end

  def issue_params
    params.require(:issue).permit(:title, :cover_image, :issue_number)
  end

  def get_unread_contacts
    @unread_contacts = policy_scope(Contact).where(archived: false).where(read: false).order(created_at: :desc)
  end
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show]
  before_action :get_issue, only: %i[show]

  def index
    @issues = policy_scope(Issue).order(created_at: :desc)
  end

  def show
  end

  private

  def get_issue
    @issue = Issue.find(params[:id])
    authorize @issue
  end

  def issue_params
    params.require(:issue).permit(:title, :cover_image, :issue_number)
  end

end

app/views/issues/index.html.erb
<section id="issue-hero">
    <% unless @issues.empty? %>
      <div class="hero-cover tinted-image" style="background-image: url(<%= image_path @issues.first.cover_image %>)">
        <div class="color-filter">
        </div>
        <div class="feature-details">
          <h1><%= link_to issue_path(@issues.first) do %><span>Latest Issue</span><% end %></h1>
          <h2><span><%= @issues.first.title %></span></h2>
        </div>
      </div>
    <% end %>

</section>

<section id="issue-index">
  <div class="issue-index">
    <div class="index-header">

    </div>
    <h3>Recent Issues</h3>

    <div class="issue-cards">
      <% unless @issues.empty? %>
        <% @issues.each do |issue| %>
          <div class="issue-card" style="background-image: url(<%= image_path issue.cover_image if issue.cover_image.present? %>)">
          <%#= issue.issue_number %>
            <div class="color-filter">
            </div>
            <div class="issue-card-content">
              <h1><span class="media-title"><%= link_to issue.title, issue_path(issue) %></span></h1>

            </div>
          </div>
        <% end %>
      <% end %>
    </div>

  </div>
</section>

app/views/issues/show.html.erb
<div class="issue-show-container">
  <div class="cover-image" style="background-image: url(<%= image_path @issue.cover_image %>)">
    <%#= image_tag(@issue.cover_image_url) %>
    <div class="color-filter"></div>
  </div>
  <div class="media-card-container">
<!--     <div class="issue-nav">

    </div> -->
    <% @issue.medias.each do |media| %>
      <div class="media-card">
        <div class="media-cover-img">
          <% if media.cover_image.present? %>
            <%= image_tag media.cover_image_url %>
            <div class="color-filter" style="top: -150px;"></div>
          <% else %>
            <div class="color-filter" style="top: 0px"></div>
          <% end %>
        </div>
        <div class="media-card-content">
          <h6 class="date">
            <%= media.date_published.strftime('%d %b, %Y') %>
          </h6>

          <h2>
            <%= link_to issue_media_path(@issue, media) do %>
              <span class="media-title"><%= media.title %></span>
            <% end %>
          </h2>

          <h6 class="author">by <strong><%= media.users.first.first_name %> <%= media.users.first.last_name %></strong></h6>
          <p class="blurb"><%= media.blurb %></p>
        </div>
      </div>
    <% end %>
  </div>
</div>