config/routes.rb
Rails.application.routes.draw do

  get 'contacts/new'
  get 'contacts/create'
  devise_for :users

  namespace :admin do
    get '', to: 'dashboard#index', as: '/'
    resources :issues
    resources :medias

    get 'users', to: 'registrations#index', as: 'users'
    get 'users/new', to: 'registrations#new', as: 'new_user'
    post 'users', to: 'registrations#create', as: 'create_user'
    get 'users/:id/edit', to: 'registrations#edit', as: 'edit_user'
    put 'users/:id/update', to:'registrations#update', as: 'update_user'
    delete 'users/:id', to: 'registrations#destroy', as:  'delete_user'

    get 'inbox', to: 'contacts#index', as: 'inbox'
    get 'toggle', to: 'contacts#toggle_read', as: 'toggle_read'
    get 'toggle_archived', to: 'contacts#toggle_archived', as: 'toggle_archived'

  end

  root to: 'issues#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :issues, only: [:index, :show] do
    resources :medias, only: [:index, :show]
  end

  resources :contacts, only: [:new, :create]
  get 'about', to: 'pages#about', as: 'about'
  get 'contact', to: 'pages#contact', as: 'contact'
  get 'news', to: 'pages#news', as: 'news'
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController
  before_action :authenticate_user!
  def index
    @issues = Issue.all.sort_by &:created_at
    @medias = Media.all.sort_by &:created_at
    @unread_contacts = policy_scope(Contact).where(archived: false).where(read: false).order(created_at: :desc)

    # binding.pry
  end
end

app/views/admin/dashboard/index.html.erb
<div class="admin">
  <h2>Welcome to the dashboard, <%= current_user.first_name %></h2>

  <div class="admin-section admin-issues">
    <h4>
      <span class="underline">Recent Issues</span>
      <div>
        <%= link_to new_admin_issue_path do %>
          <i class="fas fa-plus-circle"></i>
        <% end %>
      </div>
    </h4>
    <% if @issues.empty? %>
      <p>There are no issues yet.</p>
    <% else %>
      <% @issues.reverse.each do |issue| %>
        <div class="admin-card admin-issue-card">
          <h6><%= link_to issue_path(issue) do %><%= issue.title %><% end %></h6>
          <div class="buttons">
            <%= link_to 'Edit', edit_admin_issue_path(issue), class: 'btn-edit' %>
            <%= link_to admin_issue_path(issue), method: :destroy do %>
              <i class="far fa-trash-alt"></i>
            <% end %>

          </div>
        </div>
      <% end %>
    <% end %>
  </div>

  <div class="admin-section admin-medias">
    <h4>
      <span class="underline">Recent Media</span>
      <div>
        <%= link_to new_admin_media_path do %>
          <i class="fas fa-plus-circle"></i>
        <% end %>
      </div>
    </h4>
    <% if @medias.empty? %>
      <p>There are no articles yet.</p>
    <% else %>
      <% @medias.reverse.each do |media| %>
        <div class="admin-card admin-media-card">
          <h6><%= media.title %></h6>
          <div class="buttons">
            <%= link_to issue_path(media.issue) do %>
              <span class="issue">
                <%= media.issue.title %>
              </span>
            <% end %>
            <%= link_to 'Edit', edit_admin_media_path(media), class: 'btn-edit button' %>
            <%= link_to admin_media_path(media), method: :delete do %>
              <i class="far fa-trash-alt"></i>
            <% end %>
          </div>

        </div>
      <% end %>
    <% end %>
  </div>

</div>