config/routes.rb
Rails.application.routes.draw do

  get 'contacts/new'
  get 'contacts/create'
  devise_for :users

  namespace :admin do
    get '', to: 'dashboard#index', as: '/'
    resources :issues
    resources :medias

    get 'users', to: 'registrations#index', as: 'users'
    get 'users/new', to: 'registrations#new', as: 'new_user'
    post 'users', to: 'registrations#create', as: 'create_user'
    get 'users/:id/edit', to: 'registrations#edit', as: 'edit_user'
    put 'users/:id/update', to:'registrations#update', as: 'update_user'
    delete 'users/:id', to: 'registrations#destroy', as:  'delete_user'

    get 'inbox', to: 'contacts#index', as: 'inbox'
    get 'toggle', to: 'contacts#toggle_read', as: 'toggle_read'
    get 'toggle_archived', to: 'contacts#toggle_archived', as: 'toggle_archived'

  end

  root to: 'issues#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :issues, only: [:index, :show] do
    resources :medias, only: [:index, :show]
  end

  resources :contacts, only: [:new, :create]
  get 'about', to: 'pages#about', as: 'about'
  get 'contact', to: 'pages#contact', as: 'contact'
  get 'news', to: 'pages#news', as: 'news'
end

app/views/shared/_admin_nav.html.erb
<div class="sidebar-sticky wide-nav admin-nav">
  <div>
    <%= link_to root_path do %>
      <div class="logo-container" style="background-image: url(<%= image_path 'ninetwenty-logo.png' %>)">

      </div>
    <% end %>

    <ul class="flex-column">
      <%= link_to admin_path do %>
        <li class="nav-item
          <% if params[:controller] == 'admin/dashboard' && params[:action] == 'index' %>
            active
          <% end %>
        ">
          <i class="fas fa-tachometer-alt"></i>
          Dashboard
        </li>
      <% end %>

      <!-- I N B O X -->
      <%= link_to admin_inbox_path do %>
        <li class="nav-item inbox-nav-item
          <% if params[:controller] == 'admin/contacts' && params[:action] == 'index' %>
            active
          <% end %>
        ">
          <div>
            <i class="fas fa-inbox"></i>
            Inbox
          </div>
          <% if @unread_contacts.present? %>
            <div class="notification">
              <%= @unread_contacts.size %>
            </div>
          <% end %>
        </li>
      <% end %>

      <!-- U S E R S -->
      <li class="nav-item item-toggle" id="users-toggle">
        <i class="fas fa-user"></i>
        Users
      </li>

      <%= link_to admin_users_path do %>
        <li class="nav-item sub-nav-item users-toggle
          <% if params[:controller] == 'admin/registrations' && params[:action] == 'index' %>
            active
          <% elsif params[:controller] == 'admin/registrations' %>
            show
          <% end %>">
          All Users
        </li>
      <% end %>

      <%= link_to admin_new_user_path do %>
        <li class="nav-item sub-nav-item users-toggle
          <% if params[:controller] == 'admin/registrations' && params[:action] == 'new' %>
            active
          <% elsif params[:controller] == 'admin/registrations' %>
            show
          <% end %>">
          Add New
        </li>
      <% end %>

      <!-- I S S U E S -->
      <li class="nav-item item-toggle" id="issues-toggle">
        <i class="fas fa-book-open"></i>
        Issues
      </li>
      <%= link_to admin_issues_path do %>
        <li class="nav-item sub-nav-item issues-toggle
          <% if params[:controller] == 'admin/issues' && params[:action] == 'index' %>
            active
          <% elsif params[:controller] == 'admin/issues'%>
            show
          <% end %>">
          All Issues
        </li>
      <% end %>

      <%= link_to new_admin_issue_path do %>
        <li class="nav-item sub-nav-item issues-toggle
        <% if params[:controller] == 'admin/issues' && params[:action] == 'new' %>
          active
        <% elsif params[:controller] == 'admin/issues'%>
          show
        <% end %>">
          Add New
        </li>
      <% end %>


      <!-- M E D I A -->
      <li class="nav-item item-toggle" id="media-toggle">
        <i class="fas fa-file"></i>
        Media
      </li>

      <%= link_to admin_medias_path do %>
        <li class="nav-item sub-nav-item media-toggle
          <% if params[:controller] == 'admin/medias' && params[:action] == 'index'%>
            active
          <% elsif params[:controller] == 'admin/medias'%>
            show
          <% end %>">
          All Media
        </li>
      <% end %>

      <%= link_to new_admin_media_path do %>
        <li class="nav-item sub-nav-item media-toggle
        <% if params[:controller] == 'admin/medias' && params[:action] == 'new' %>
          active
        <% elsif params[:controller] == 'admin/medias' %>
          show
        <% end %>">
          Add New
        </li>
      <% end %>

      <%= link_to destroy_user_session_path, method: :delete do %>
        <li class="nav-item">
          <i class="fas fa-sign-out-alt"></i>
          Log Out
        </li>
      <% end %>

    </ul>
  </div>
</div>

app/views/shared/_sidenav_slim.html.erb
<div class="slim-nav">
  <%= link_to root_path do %>
    <div class="logo-container" style="background-image: url(<%= image_path 'ninetwenty-logo-slim.png' %>)">
    </div>
  <% end %>
  <div class="social-container">
    <ul class="social-list">
      <li><i class="fab fa-facebook"></i></li>
      <li><i class="fab fa-twitter"></i></li>
    </ul>
  </div>
</div>

app/views/shared/_sidenav_wide.html.erb
<div class="wide-nav">
  <div>
    <div class="logo-container" style="background-image: url(<%= image_path 'ninetwenty-logo.png' %>)">
    </div>
    <ul>
      <li><%= link_to 'issues', root_path %></li>
      <li><%= link_to 'podcasts', '#' %></li>
      <li><%= link_to 'news', '#' %></li>
      <li><%= link_to 'about', about_path %></li>
      <li><%= link_to 'contact', contact_path %></li>
    </ul>
  </div>
  <div class="social-container">
    <ul class="social-list">
      <li><i class="fab fa-facebook"></i></li>
      <li><i class="fab fa-twitter"></i></li>
    </ul>
  </div>
</div>