config/routes.rb
Rails.application.routes.draw do

  get 'contacts/new'
  get 'contacts/create'
  devise_for :users

  namespace :admin do
    get '', to: 'dashboard#index', as: '/'
    resources :issues
    resources :medias

    get 'users', to: 'registrations#index', as: 'users'
    get 'users/new', to: 'registrations#new', as: 'new_user'
    post 'users', to: 'registrations#create', as: 'create_user'
    get 'users/:id/edit', to: 'registrations#edit', as: 'edit_user'
    put 'users/:id/update', to:'registrations#update', as: 'update_user'
    delete 'users/:id', to: 'registrations#destroy', as:  'delete_user'

    get 'inbox', to: 'contacts#index', as: 'inbox'
    get 'toggle', to: 'contacts#toggle_read', as: 'toggle_read'
    get 'toggle_archived', to: 'contacts#toggle_archived', as: 'toggle_archived'

  end

  root to: 'issues#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :issues, only: [:index, :show] do
    resources :medias, only: [:index, :show]
  end

  resources :contacts, only: [:new, :create]
  get 'about', to: 'pages#about', as: 'about'
  get 'contact', to: 'pages#contact', as: 'contact'
  get 'news', to: 'pages#news', as: 'news'
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :email,
    :presence => :true,
    :format => {
      :with => /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i,
      :message => "must be a valid email address"
    }
  validates :message, :name, :presence => :true

  def get_unread
    @contacts = self.contacts.map do |contact|
      contact unless contact.read
    end
    @contacts.reject { |item| item.nil? || item == '' }
  end

end

app/controllers/admin/contacts_controller.rb
class Admin::ContactsController < ApplicationController
  before_action :authenticate_user!
  before_action :get_contact, only: [:toggle_read, :toggle_archived]

  def index
    @partial = whitelisted_partial
    @contacts = policy_scope(Contact).where(archived: false).order(created_at: :desc)
    @unread_contacts = policy_scope(Contact).where(archived: false).where(read: false).order(created_at: :desc)
    @archived_contacts = policy_scope(Contact).where(archived: true).order(created_at: :desc)
  end

  def toggle_read
    @contact.read = !@contact.read
    @contact.save
    redirect_to admin_inbox_path
  end

  def toggle_archived
    @contact.archived = !@contact.archived
    @contact.save
    redirect_to admin_inbox_path
  end

  private

  def get_contact
    @contact = Contact.find(params[:id])
    authorize @contact
  end

  def whitelisted_partial
    if params[:view] == 'archived'
      'admin/contacts/archived'
    else
      'admin/contacts/unarchived'
    end
  end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :get_contact, only: [:toggle_read]

  def new
    @contact = Contact.new
    authorize @contact
  end

  def create
    @contact = Contact.new(contact_params)
    @contact.read = false
    @contact.archived = false
    authorize @contact

    if @contact.save
      ContactsMailer.new_contact_message(@contact).deliver
      render :thanks
    else
      redirect_to contact_path
    end
  end

  def thanks
  end

  private


  def contact_params
    params.require(:contact).permit(:name, :email, :message)
  end

end

app/views/admin/contacts/_archived.html.erb
<h2>Archived Messages</h2>
<%= render 'admin/contacts/inbox_nav' %>

  <div class="inbox-container">

    <% if archived_contacts.nil? %>
      <p>There are no archived messages.</p>
    <% else %>
      <% archived_contacts.each do |contact| %>
        <div class="contact-card <% if contact.read %>read<% else %>unread<% end %>">


          <div class="head">
            <div class="status">
              <% if contact.read %>
                read
              <% else %>
                <span class="unread">unread</span>
              <% end %>
            </div>
            <span><%= contact.name %></span>
          </div>
          <div class="body">

            <span class="message truncate"><%= contact.message.truncate(50) %></span>
            <span class="message full"><%= contact.message %></span>

            <div>
              <div id="hover-menu">
                <ul>
                  <%= link_to admin_toggle_archived_path(id: contact.id, view: 'archived') do %>
                    <li><i class="fas fa-archive"></i></li>
                  <% end %>

                  <% if contact.read %>
                    <%= link_to admin_toggle_read_path(id: contact.id, view: 'archived') do %>

                      <li><i class="fas fa-envelope"></i></li>
                      <% end %>
                  <% else %>
                    <li>
                      <%= link_to admin_toggle_read_path(id: contact.id, view: 'archived') do %>
                      <i class="fas fa-envelope-open"></i>
                      <% end %>
                    </li>
                  <% end %>
                </ul>
              </div>
              <span class="date"><%= contact.created_at.strftime('%d %b') %></span>
            </div>
          </div>


        </div>
      <% end %>
    <% end %>
  </div>

app/views/admin/contacts/_inbox_nav.html.erb
<div class="inbox-nav">
  <ul>
    <%= link_to admin_inbox_path(view: 'inbox') do %>
      <li><i class="fas fa-inbox"></i></li>
    <% end %>

    <%= link_to admin_inbox_path(view: 'archived') do %>
      <li><i class="fas fa-box-open"></i></li>
    <% end %>
  </ul>
</div>

app/views/admin/contacts/_unarchived.html.erb
  <h2>Inbox (<%= unread_contacts.size %>)</h2>
  <%= render 'admin/contacts/inbox_nav' %>
  <div class="inbox-container">

    <% if contacts.nil? %>
      <p>There are no messages.</p>
    <% else %>
      <% contacts.each do |contact| %>
        <div class="contact-card <% if contact.read %>read<% else %>unread<% end %>">


          <div class="head">
            <div class="status">
              <% if contact.read %>
                read
              <% else %>
                <span class="unread">unread</span>
              <% end %>
            </div>
            <span><%= contact.name %></span>
          </div>
          <div class="body">

            <span class="message truncate"><%= contact.message.truncate(50) %></span>
            <span class="message full"><%= contact.message %></span>

            <div>
              <div id="hover-menu">
                <ul>
                  <%= link_to admin_toggle_archived_path(:id => contact.id) do %>
                    <li><i class="fas fa-archive"></i></li>
                  <% end %>

                  <% if contact.read %>
                    <%= link_to admin_toggle_read_path(:id => contact.id) do %>

                      <li><i class="fas fa-envelope"></i></li>
                      <% end %>
                  <% else %>
                    <li>
                      <%= link_to admin_toggle_read_path(:id => contact.id) do %>
                      <i class="fas fa-envelope-open"></i>
                      <% end %>
                    </li>
                  <% end %>
                </ul>
              </div>
              <span class="date"><%= contact.created_at.strftime('%d %b') %></span>
            </div>
          </div>


        </div>
      <% end %>
    <% end %>
  </div>

app/views/admin/contacts/index.html.erb
<div class="admin">
  <%= render :partial => @partial, locals: {
      contacts: @contacts,
      unread_contacts: @unread_contacts,
      archived_contacts: @archived_contacts}
  %>
</div>